//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas
    {
        public int salidaId { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> tipo_salida { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
    
        public virtual Tipo_salida Tipo_salida1 { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
